### ISSUE TITLE
Exception is thrown when the assignment is missing

### ISSUE THREAD

**Issue by Jokeswar** [Jokeswar/vmchecker-next#12]
When the activity associated with the VMChecker block (the assignment) is missing, an exception is thrown if the user tries to access the grades section.

The error is thrown from the following [piece of code](https://github.com/open-education-hub/vmchecker-next/blob/master/block_vmchecker.php#L192). This happens since "MUST_EXIST" is given as a parameter and it throws an error if the assignment is missing (See [docs](https://github.com/moodle/moodle/blob/main/lib/datalib.php#L1298)).

There are 2 possible solutions:
- Use "IGNORE_MISSING"
- Guard with a `try-catch` construct

There might be other places where this behavior could cause issues. For example:
-  https://github.com/open-education-hub/vmchecker-next/blob/master/block_vmchecker.php#L64

**Comment by darius-m** [comment]
Should be fixed in #13 .
